"""
===========================================================
Employee Skill Intelligence Assistant (ESIA)
Professional Resume PDF Generator
===========================================================
"""

from reportlab.lib import colors
from reportlab.lib.enums import TA_CENTER, TA_LEFT
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import inch
from reportlab.platypus import (
    SimpleDocTemplate,
    Paragraph,
    Spacer,
    Table,
    TableStyle
)

from .config import RESUME_DIR


class PDFGenerator:

    def __init__(self):

        styles = getSampleStyleSheet()

        # --------------------------------------------------
        # Employee Name
        # --------------------------------------------------

        self.name_style = ParagraphStyle(
            "NameStyle",
            parent=styles["Heading1"],
            fontName="Helvetica-Bold",
            fontSize=22,
            leading=26,
            alignment=TA_CENTER,
            textColor=colors.HexColor("#003366"),
            spaceAfter=4,
        )

        # --------------------------------------------------
        # Designation
        # --------------------------------------------------

        self.role_style = ParagraphStyle(
            "RoleStyle",
            parent=styles["Heading2"],
            fontName="Helvetica",
            fontSize=13,
            alignment=TA_CENTER,
            textColor=colors.HexColor("#555555"),
            spaceAfter=14,
        )

        # --------------------------------------------------
        # Section Heading
        # --------------------------------------------------

        self.section_style = ParagraphStyle(
            "SectionStyle",
            parent=styles["Heading2"],
            fontName="Helvetica-Bold",
            fontSize=13,
            textColor=colors.HexColor("#003366"),
            spaceBefore=12,
            spaceAfter=8,
        )

        # --------------------------------------------------
        # Normal Text
        # --------------------------------------------------

        self.normal_style = ParagraphStyle(
            "NormalStyle",
            parent=styles["BodyText"],
            fontName="Helvetica",
            fontSize=10,
            leading=16,
            alignment=TA_LEFT,
        )

        # --------------------------------------------------
        # Small Text
        # --------------------------------------------------

        self.small_style = ParagraphStyle(
            "SmallStyle",
            parent=styles["BodyText"],
            fontName="Helvetica",
            fontSize=9,
            textColor=colors.grey,
        )

        # --------------------------------------------------
        # Bullet Style
        # --------------------------------------------------

        self.bullet_style = ParagraphStyle(
            "BulletStyle",
            parent=styles["BodyText"],
            fontName="Helvetica",
            fontSize=10,
            leftIndent=18,
            bulletIndent=8,
            leading=16,
        )

    # =====================================================
    # Page Number
    # =====================================================

    def add_page_number(self, canvas, doc):

        canvas.saveState()

        canvas.setFont("Helvetica", 9)

        canvas.setFillColor(colors.grey)

        canvas.drawRightString(
            560,
            20,
            f"Page {doc.page}"
        )

        canvas.drawString(
            40,
            20,
            "Generated by ESIA Resume Generator"
        )

        canvas.restoreState()

    # =====================================================
    # Section Title
    # =====================================================

    def add_section_title(self, story, title):

        story.append(
            Spacer(1, 0.15 * inch)
        )

        story.append(
            Paragraph(
                title.upper(),
                self.section_style
            )
        )

        line = Table(
            [[""]],
            colWidths=[520]
        )

        line.setStyle(
            TableStyle([
                ("LINEBELOW", (0, 0), (-1, -1), 1, colors.HexColor("#8DB3D8"))
            ])
        )

        story.append(line)

        story.append(
            Spacer(1, 0.08 * inch)
        )

    # =====================================================
    # Resume Header
    # =====================================================

    def add_header(self, story, resume):

        header = resume["header"]

        # Employee Name

        story.append(
            Paragraph(
                header["name"],
                self.name_style
            )
        )

        # Designation

        story.append(
            Paragraph(
                header["designation"],
                self.role_style
            )
        )

        # Contact Information

        self.add_contact_info(
            story,
            header
        )

        story.append(
            Spacer(1, 0.20 * inch)
        )

    # =====================================================
    # Contact Table
    # =====================================================

    def add_contact_info(self, story, header):

        data = [

            ["Email", header["email"]],

            ["Location", header["location"]],

            ["Experience", f"{header['experience']} Years"],

            ["Domain", header["domain"]]

        ]

        table = Table(
            data,
            colWidths=[90, 400]
        )

        table.setStyle(

            TableStyle(

                [

                    ("BACKGROUND", (0, 0), (0, -1), colors.HexColor("#F3F6FA")),

                    ("TEXTCOLOR", (0, 0), (0, -1), colors.HexColor("#003366")),

                    ("FONTNAME", (0, 0), (0, -1), "Helvetica-Bold"),

                    ("FONTNAME", (1, 0), (1, -1), "Helvetica"),

                    ("BOTTOMPADDING", (0, 0), (-1, -1), 6),

                    ("TOPPADDING", (0, 0), (-1, -1), 6),

                    ("GRID", (0, 0), (-1, -1), 0.25, colors.lightgrey),

                ]

            )

        )

        story.append(table)
    # =====================================================
    # Professional Summary
    # =====================================================

    def add_summary(self, story, resume):

        self.add_section_title(
            story,
            "Professional Summary"
        )

        story.append(
            Paragraph(
                resume["summary"],
                self.normal_style
            )
        )

    # =====================================================
    # Technical Skills
    # =====================================================

    def add_skills(self, story, resume):

        self.add_section_title(
            story,
            "Technical Skills"
        )

        data = [
            [
                Paragraph("<b>Category</b>", self.normal_style),
                Paragraph("<b>Skills</b>", self.normal_style)
            ]
        ]

        for category, skills in resume["technical_skills"].items():

            skill_text = ", ".join(
                skill["skill"]
                for skill in skills
            )

            data.append([
                Paragraph(category, self.normal_style),
                Paragraph(skill_text, self.normal_style)
            ])

        table = Table(
            data,
            colWidths=[120, 380]
        )

        table.setStyle(

            TableStyle([

                # Header
                ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#EEF4FB")),
                ("TEXTCOLOR", (0, 0), (-1, 0), colors.HexColor("#234E70")),
                ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),

                # Body
                ("BACKGROUND", (0, 1), (-1, -1), colors.white),
                ("TEXTCOLOR", (0, 1), (-1, -1), colors.black),

                # Borders
                ("GRID", (0, 0), (-1, -1), 0.25, colors.HexColor("#E2E8F0")),

                # Padding
                ("TOPPADDING", (0, 0), (-1, -1), 8),
                ("BOTTOMPADDING", (0, 0), (-1, -1), 8),
                ("LEFTPADDING", (0, 0), (-1, -1), 8),
                ("RIGHTPADDING", (0, 0), (-1, -1), 8),

                ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),

            ])
        )

        story.append(table)

    # =====================================================
    # Projects
    # =====================================================

    def add_projects(self, story, resume):

        self.add_section_title(
            story,
            "Professional Experience"
        )

        for project in resume["projects"]:

            self.add_project(
                story,
                project
            )

            story.append(
                Spacer(1, 0.20 * inch)
            )

    # =====================================================
    # Single Project
    # =====================================================

    def add_project(self, story, project):

        story.append(

            Paragraph(

                f"<b>{project['project_name']}</b>",

                self.section_style

            )

        )

        info = [

            ["Client", project["client"]],

            ["Role", project["role"]],

            ["Duration", project["duration"]],

            ["Technology", project["technology"]]

        ]

        table = Table(
            info,
            colWidths=[90, 410]
        )

        table.setStyle(

            TableStyle([

                ("BACKGROUND", (0, 0), (0, -1), colors.HexColor("#F3F6FA")),

                ("TEXTCOLOR", (0, 0), (0, -1), colors.HexColor("#003366")),

                ("FONTNAME", (0, 0), (0, -1), "Helvetica-Bold"),

                ("GRID", (0, 0), (-1, -1), 0.25, colors.lightgrey),

                ("BOTTOMPADDING", (0, 0), (-1, -1), 5),

                ("TOPPADDING", (0, 0), (-1, -1), 5)

            ])

        )

        story.append(table)

        story.append(
            Spacer(1, 0.08 * inch)
        )

        story.append(

            Paragraph(

                "<b>Key Responsibilities</b>",

                self.normal_style

            )

        )

        self.add_project_responsibilities(
            story,
            project["responsibilities"]
        )

    # =====================================================
    # Responsibilities
    # =====================================================

    def add_project_responsibilities(
        self,
        story,
        responsibilities
    ):

        for responsibility in responsibilities:

            story.append(

                Paragraph(

                    f"• {responsibility}",

                    self.bullet_style

                )

            )
        # =====================================================
    # Certifications
    # =====================================================

    def add_certifications(self, story, resume):

        certifications = resume.get("certifications", [])

        if not certifications:
            return

        self.add_section_title(
            story,
            "Professional Certifications"
        )

        data = [
            [
                Paragraph("<b>Certification</b>", self.normal_style),
                Paragraph("<b>Status</b>", self.normal_style),
                Paragraph("<b>Score</b>", self.normal_style)
            ]
        ]

        for cert in certifications:

            data.append([
                Paragraph(cert["name"], self.normal_style),
                Paragraph(cert["status"], self.normal_style),
                Paragraph(str(cert.get("score", "-")), self.normal_style)
            ])

        table = Table(
            data,
            colWidths=[300, 100, 80]
        )

        table.setStyle(

            TableStyle([

                ("BACKGROUND", (0,0), (-1,0), colors.HexColor("#003366")),

                ("TEXTCOLOR", (0,0), (-1,0), colors.white),

                ("FONTNAME", (0,0), (-1,0), "Helvetica-Bold"),

                ("GRID", (0,0), (-1,-1), 0.25, colors.grey),

                ("BACKGROUND", (0,1), (-1,-1), colors.whitesmoke),

                ("BOTTOMPADDING", (0,0), (-1,-1), 6),

                ("TOPPADDING", (0,0), (-1,-1), 6)

            ])

        )

        story.append(table)

    # =====================================================
    # Training
    # =====================================================

    def add_training(self, story, resume):

        trainings = resume.get("trainings", [])

        if not trainings:
            return

        self.add_section_title(
            story,
            "Training"
        )

        data = [
            [
                Paragraph("<b>Course</b>", self.normal_style),
                Paragraph("<b>Technology</b>", self.normal_style),
                Paragraph("<b>Provider</b>", self.normal_style),
                Paragraph("<b>Score</b>", self.normal_style),
            ]
        ]

        for training in trainings:

            score = (
                str(training["score"])
                if training["score"] not in [None, "", 0]
                else "-"
            )

            data.append([
                Paragraph(training["course"], self.normal_style),
                Paragraph(training["technology"], self.normal_style),
                Paragraph(training["provider"], self.normal_style),
                Paragraph(score, self.normal_style),
            ])

        table = Table(
            data,
            colWidths=[180, 120, 150, 50]
        )

        table.setStyle(
            TableStyle([
            
                # Header
                ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#EEF4FB")),
                ("TEXTCOLOR", (0, 0), (-1, 0), colors.HexColor("#234E70")),
                ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),

                # Body
                ("BACKGROUND", (0, 1), (-1, -1), colors.white),
                ("TEXTCOLOR", (0, 1), (-1, -1), colors.black),

                # Borders
                ("GRID", (0, 0), (-1, -1), 0.25, colors.HexColor("#E2E8F0")),

                # Padding
                ("TOPPADDING", (0, 0), (-1, -1), 8),
                ("BOTTOMPADDING", (0, 0), (-1, -1), 8),
                ("LEFTPADDING", (0, 0), (-1, -1), 8),
                ("RIGHTPADDING", (0, 0), (-1, -1), 8),

                ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),

            ])

        )

        story.append(table)
    # =====================================================
    # Education
    # =====================================================

    def add_education(self, story, resume):

        education = resume.get("education", [])

        if not education:
            return

        self.add_section_title(
            story,
            "Education"
        )

        edu = education[0]

        data = [

            ["Degree", edu["degree"]],

            ["Specialization", edu["branch"]],

            ["University", edu["university"]],

            ["Passing Year", str(edu["passing_year"])],


        ]

        table = Table(
            data,
            colWidths=[120, 380]
        )

        table.setStyle(
            TableStyle([

                # Header
                ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#F5F9FD")),
                ("TEXTCOLOR", (0, 0), (-1, 0), colors.HexColor("#1F4E79")),
                ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
                ("FONTSIZE", (0, 0), (-1, 0), 10),

                # Body
                ("BACKGROUND", (0, 1), (-1, -1), colors.white),
                ("TEXTCOLOR", (0, 1), (-1, -1), colors.black),

                # Borders
                ("GRID", (0, 0), (-1, -1), 0.30, colors.HexColor("#D6E2EE")),

                # Alignment
                ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),

                # Padding
                ("TOPPADDING", (0, 0), (-1, -1), 8),
                ("BOTTOMPADDING", (0, 0), (-1, -1), 8),
                ("LEFTPADDING", (0, 0), (-1, -1), 8),
                ("RIGHTPADDING", (0, 0), (-1, -1), 8),

            ])
        )

        story.append(table)

    # =====================================================
    # Achievements
    # =====================================================

    def add_achievements(self, story, resume):

        achievements = resume.get("achievements", [])

        if not achievements:
            return

        self.add_section_title(
            story,
            "Achievements"
        )

        for achievement in achievements:

            story.append(

                Paragraph(

                    f"• {achievement}",

                    self.bullet_style

                )

            )

    # =====================================================
    # Career Highlights
    # =====================================================

    def add_career_highlights(self, story, resume):

        story.append(
            Spacer(1, 0.15 * inch)
        )

        self.add_section_title(
            story,
            "Career Highlights"
        )

        highlights = [

            "Strong experience in enterprise software development.",

            "Hands-on expertise in Agile Scrum methodologies.",

            "Excellent analytical and problem-solving skills.",

            "Experience working with cross-functional global teams.",

            "Committed to delivering high-quality scalable solutions."

        ]

        for item in highlights:

            story.append(

                Paragraph(

                    f"• {item}",

                    self.bullet_style

                )

            )
    
    def generate(self, resume):

        header = resume["header"]

        file_name = (
            f"EMP{header['employee_id']}_{header['name'].replace(' ', '_')}.pdf"
        )

        pdf_path = RESUME_DIR / file_name

        doc = SimpleDocTemplate(
            str(pdf_path),
            rightMargin=0.55 * inch,
            leftMargin=0.55 * inch,
            topMargin=0.60 * inch,
            bottomMargin=0.60 * inch,
            title=f"Resume - {header['name']}",
            author="Employee Skill Intelligence Assistant (ESIA)",
            subject="Professional Resume"
        )

        story = []

        # Header
        self.add_header(story, resume)

        # Summary
        self.add_summary(story, resume)

        # Skills
        self.add_skills(story, resume)

        # Projects
        self.add_projects(story, resume)

        # Certifications
        self.add_certifications(story, resume)

        # Training
        self.add_training(story, resume)

        # Education
        self.add_education(story, resume)

        # Achievements
        self.add_achievements(story, resume)

        # Career Highlights
        self.add_career_highlights(story, resume)

        doc.build(
            story,
            onFirstPage=self.add_page_number,
            onLaterPages=self.add_page_number
        )

        return pdf_path   

    def generate_all(self, resumes):

        generated = []

        for resume in resumes:

            pdf = self.generate(resume)

            generated.append(pdf)

        return generated

    def print_summary(self, resumes):

        print("=" * 60)
        print("Resume Generation Summary")
        print("=" * 60)

        print(f"Total Resumes : {len(resumes)}")

        print(f"Output Folder : {RESUME_DIR}")

        print("=" * 60)                 