API_BASE_URL = "http://127.0.0.1:8000"

APP_NAME = "ESIRA"

APP_SUBTITLE = "Employee Skill Intelligence & Recruitment Assistant"

PRIMARY_COLOR = "#2563EB"

SECONDARY_COLOR = "#10B981"

BACKGROUND_COLOR = "#F8FAFC"

CARD_RADIUS = "12px"